:expect @count() == 0
:expect @count(1) == 1
:expect @count(2) == 1
:expect @count('string') == 0
:expect @count(1, 1) == 2
:expect @count(1, 2) == 2
:expect @count(2, 2) == 2
:expect @count(1, 'string') == 1
:expect @count('string', 1) == 1
:expect @count(0) == 1
:expect @count(0, 'string') == 1
:expect @count(0, 'string', 0) == 2
:fill a0:d10 1 1
let e0 = @width(a0:d10) * @height(a0:d10)
:expect @count(a0:d10) == e0
:expect @count(a0:d10, 1, 2, 3) == e0 + 3
:expect @count('string', a0:d10) == e0
:expect @count([]) == 0
:expect @count([1]) == 1
:expect @count([1], [1]) == 2
:expect @count([1, 2]) == 2
:expect @count([1, 2, 3]) == 3
:expect @count([], 1) == 1
:expect @count(1, []) == 1
:expect @count([1, 2], 1, 3) == 4
:expect @count(g10:g100) == 0
let g50 = 3
:expect @count(g10:g100) == 1
let g51 = 'howdy'
:expect @count(g10:g100) == 1
:expect (@range(1, 10) |> @filter(|x| x % 2 == 0) |> @count()) == 4 -- Range is end exclusive
:expect @count(nil) == 0
:expect @count(|x| x * 2) == 0
:expect @count(@count) == 0
:expect @count(@sum) == 0
:expect @count(@sum(3)) == 1
