let a0 = (|| 2)()
:expect a0 == 2
let a0 = (|x| x)(5)
:expect a0 == 5
let a0 = || 3
let b0 = a0()
:expect b0 == 3
let a0 = |x| 5
:expect-error b0 -- Not enough arguments
let b0 = a0(3)
:expect b0 == 5
let a0 = |x| x * x
:expect b0 == 9
let c0 = 9
let b0 = a0(c0)
:expect b0 == 81
let a0 = |x, y| x * y
let b0 = a0()
:expect-error b0
let b0 = a0(1)
:expect-error b0
let b0 = a0(5, 3)
:expect b0 == 15
let a0 = |x, y| y * y
:expect b0 == 9
let a0 = |x, y, z| x * y + z
let b0 = a0(3, 5, 10)
:expect b0 == 25

-- Closures
:expect (|x| (|| x))(3)() == 3
let a0 = |x| |y| x + y
let b0 = a0(5)
:expect b0(3) == 8
:expect b0(11) == 16
let a0 = |x| x(3)
:expect a0(|x| 5 * x) == 15
