let a0 = (|| 2)()
:expect a0 == 2
let a0 = (|x| x)(5)
:expect a0 == 5
let a0 = || 3
let b0 = a0()
:expect b0 == 3
let a0 = |x| 5
:expect-error b0 -- Not enough arguments
let b0 = a0(3)
:expect b0 == 5
let a0 = |x| x * x
:expect b0 == 9
let c0 = 9
let b0 = a0(c0)
:expect b0 == 81
let a0 = |x, y| x * y
let b0 = a0()
:expect-error b0
let b0 = a0(1)
:expect-error b0
let b0 = a0(5, 3)
:expect b0 == 15
let a0 = |x, y| y * y
:expect b0 == 9
let a0 = |x, y, z| x * y + z
let b0 = a0(3, 5, 10)
:expect b0 == 25

-- Closures
:expect (|x| (|| x))(3)() == 3
let a0 = |x| |y| x + y
let b0 = a0(5)
:expect b0(3) == 8
:expect b0(11) == 16
let a0 = |x| x(3)
:expect a0(|x| 5 * x) == 15

-- Pipes
let a0 = |x| x * x
let b0 = |x, y| x + y
let c0 = |x, y, z| x * y + z
:expect (5 |> a0()) == 25
:expect (5 |> b0(2)) == 7
:expect (3 |> c0(5, 10)) == 25
:expect (5 |> a0() |> a0()) == 625
:expect (5 |> a0() |> b0(1)) == 26

-- Function values
let a0 = |x| x * x
let b0 = &a0
let c0 = 5 |> a0 |> **b0
:expect c0 == 625
