:fill a0:d10 1
:expect @sum(a0:d10) == @width(a0:d10) * @height(a0:d10)
:expect (a0:d10 |> @sum()) == @width(a0:d10) * @height(a0:d10)
:expect (a0:d10 |> @map(|x| *x * 2) |> @sum()) == @width(a0:d10) * @height(a0:d10) * 2
:expect (a0:d10 |> @filter(|x| x == &a0 or x == &c3 or x == &d10 or x == &g5) |> @sum()) == 3
let e0 = a0:d10 |> @map(|x| *x)

let a1 = b100:d200 |> @map(|x| *x)
let a2 = @sum(*a1)
let a3 = @sum(*a1)
:y a2
:p a4
:expect-eql-number a2 0
:expect-eql-number a3 0
:expect-eql-number a4 0
let b100 = 5
:expect-eql-number a2 5
:expect-eql-number a3 5
:expect-eql-number a4 5

let a5 = [1, 2, 3, 4, 5] |> @filter(|x| x != 2) |> @count()
:expect-eql-number a5 4

:expect (@range(1, 10) |> @filter(|x| x % 2) |> @count()) == 5
:expect (@range(1, 10) |> @count()) == 9
:expect (@range(1, 10) |> @map(|x| x * 2) |> @sum()) == 2 * (@range(1, 10) |> @sum())

let a10 = (|x| |y| x + y)(3)
let b10 = [1, 2, 3] |> @filter(*a10) |> @sum()
:expect-eql-number b10 6

let A0={ identity = |x| x, double = |x| x * 2, triple = |x| x * 3 , square = |x| x * x}
let B0=A0 |> @filter(|x| x[0] == 'double' or x[0] == 'triple') |> @map(|x| x[1](4)) |> @sum()
:expect B0 == 20

:e
let a0 = b0:d10 |> @filter(|x| *x % 2 == 0) |> @any()
:expect a0 == nil
let b0 = 5
:expect a0 == nil
let d5 = 3
:expect a0 == nil
let d5 = 4
:expect a0 == 4
let d5 = 5
:expect a0 == nil

:expect @any() == nil
:expect @any(1) == 1
:expect @any(5, 4, 3, 2, 1) != nil
