:expect [1, 2, 3][0] == 1
:expect [1, 2, 3][1] == 2
:expect [1, 2, 3][2] == 3

let a0 = [1, 2, 3][0]
:expect-eql-number a0 1
let a0 = [1, 2, 3][1]
:expect-eql-number a0 2
let a0 = [1, 2, 3][2]
:expect-eql-number a0 3
let a0 = [1, 2, 3][3]
:expect-error a0
let a0 = [1, 2, 3][9999]
:expect-error a0
let a0 = [1, 2, 3][-1]
:expect-error a0
let a0 = [1, 2, 3][100000000000000000000000000000000]
:expect-error a0

let a0 = [][0]
:expect-error a0
let a0 = [1][0]
:expect-eql-number a0 1
let a0 = [1][1]
:expect-error a0

let a0 = [1, 2, 3]
let b0 = a0[0]
:expect-eql-number b0 1
let b0 = a0[1]
:expect-eql-number b0 2
let b0 = a0[2]
:expect-eql-number b0 3
let b0 = a0[3]
:expect-error b0
let b0 = a0[9999]
:expect-error b0
let b0 = a0[-1]
:expect-error b0
let b0 = a0[100000000000000000000000000000000]
:expect-error b0

let a1 = || [1, 2, 3]
:expect a1()[0] == 1
:expect a1()[1] == 2
:expect a1()[2] == 3

:expect [nil][0] == nil
:expect [[10]][0][0] == 10
:expect [[[10]]][0][0][0] == 10
:expect [[[1, [10], 1], 1], 1][0][0][1][0] == 10

let a2 = @range(1, 10) |> @filter(|x| x % 2 == 0)
:expect ([a2][0] |> @count()) == 4
:expect ([a2][0] |> @filter(|x| x < 6) |> @count()) == 2
:expect ([1, @range(1, 10) |> @filter(|x| x % 2 == 0)][1] |> @count()) == 4

:expect [1, 2, 'howdy', 4][2] == 'howdy'
let a3 = [1,] -- Trailing comma
:expect a3[0] == 1
